### ISSUE TITLE
Akka.Coordination.Azure is not able to retrieve leases

### ISSUE THREAD

**Issue by wesselkranenborg** [akkadotnet/Akka.Management#1027]
**Version Information**
Version of Akka.NET? 1.4.46
Which Akka.NET Modules? 
    <PackageReference Include="Akka.Coordination.Azure" Version="0.3.0-beta3" />

This is the configuration I enabled and after which it broke:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/4964604/202469056-77a86ac9-80ca-4163-b209-1212c1eaad52.png">

**Describe the bug**
The cluster cannot start and fails with the following message:

```
Failure communicating with the API server for owner system-state-service@10.0.9.130:12552 lease system-state-service-singleton-akkasystem-state-servicesystemsh: [Unexpected response from API server when retrieving lease StatusCode: $BadRequest. Reason: [InvalidQueryParameterValue]]. Current state: Akka.Coordination.Azure.LeaseActor+PendingRead

---

Unexpected response from API server when retrieving lease StatusCode: $BadRequest. Reason: [InvalidQueryParameterValue] Value for one of the query parameters specified in the request URI is invalid.
RequestId:2e8486b1-701e-00f4-448a-fad079000000
Time:2022-11-17T13:41:36.6520090Z
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue

Additional Information:
QueryParameterName: comp
QueryParameterValue: 
Reason: 

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:2e8486b1-701e-00f4-448a-fad079000000
Time:2022-11-17T13:41:36.6520090Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue /><Reason /></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 2e8486b1-701e-00f4-448a-fad079000000
x-ms-client-request-id: ac67f22a-1184-4406-9ad6-059971b51758
x-ms-error-code: InvalidQueryParameterValue
Date: Thu, 17 Nov 2022 13:41:36 GMT
Content-Length: 351
Content-Type: application/xml
```

**Comment by Aaronontheweb** [comment]
Thanks @wesselkranenborg - we're looking into this

**Comment by Arkatufus** [comment]
Looks like a faulty cluster singleton lease implementation, need to harden it.

**Comment by Arkatufus** [comment]
@wesselkranenborg 
This is really weird, none of the operations used inside the lease at the time of failure uses the `comp` query in its REST API call.

Can you confirm that you can use your credentials and endpoint url to upload a blob using Azure `BlobClient`?

**Comment by wesselkranenborg** [comment]
That is really weird. I use the same DefaultAzureCredential and blob service url which I also use for Akka.Persistence.Azure. And snapshots and events are correctly stored in the table and blob storage. Will try to see if I can verify this.

Or might it be a combination of these two conflicting?

**Comment by Arkatufus** [comment]
The `comp` query in the REST API were always set when the azure client needed to set them, at least that's what I've gleamed so far from the Azure source code, the issues I've seen on the web that has the same symptom (missing `comp` query) are usually caused by the client sending a REST request to a wrong URI that requires the `comp` query.
What makes this even more perplexing is the fact that your credential and URI are known to work with Azure Blob Storage. It doesn't help that the client doesn't give any hint on what went wrong, it just passes the server error along, and these errors only makes sense if you're doing a direct REST API call.

**Comment by Aaronontheweb** [comment]
@wesselkranenborg have you seen this issue occur on your end again since our last communication here? We're still scratching our heads over this issue somewhat

**Comment by wesselkranenborg** [comment]
Will try it again tomorrow and see if I can find any reasoning for this.

**Comment by wesselkranenborg** [comment]
It's still an issue, I'll send some more detailed (unfiltered) logging to you via Discord to not expose it here.

**Comment by wesselkranenborg** [comment]
This indeed solved the issue on my developer PC, looks good so far!

**Comment by Aaronontheweb** [comment]
> This indeed solved the issue on my developer PC, looks good so far!

Excellent! Thanks for letting us know and for reporting the issue.
