### ISSUE TITLE
Need to decouple Akka.Management from Akka.Hosting

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Akka.Management#1049]
Right now, because of pending Akka.Hosting API changes, Akka.Hosting is preventing Akka.Management from going out of beta. Akka.Hosting support in Akka.Management is baked into each Akka.Management plugins, and a significant API change in Akka.Hosting can have a domino effect that affect Akka.Management directly. A better approach is to split these hosting extension methods into their own separate packages instead of bundling hosting into each plugins.

**Comment by Aaronontheweb** [comment]
This won't be a long-term problem after Akka.Hosting's API is frozen.
