### ISSUE TITLE
ASP.NET vs. Akka.HTTP API Separation

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Management#17]
Do we really want this? I was trying to avoid leaking anything from AspNetCore outside the Http extesion itself. By leveraging the [Request Features](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features) via [HttpRequestMiddleware](https://github.com/akkadotnet/Akka.Management/blob/a13c7567040a44d236b513e236a98d35e2018d61/src/management/Akka.Http.Shim/Internal/HttpRequestMiddleware.cs) in the original PR, we can do these mappings at the middleware level.

Is there any limitations to that approach?

_Originally posted by @ismaelhamed in https://github.com/akkadotnet/Akka.Management/pull/13#discussion_r680319296_

**Comment by Aaronontheweb** [comment]
Wanted to capture this discussion in a new issue since it's important that we design the Akka.HTTP API appropriately.

@akkadotnet/core - what's the right level of separation between Akka.HTTP and ASP.NET from an API exposure point of view? See #13 for details.

**Comment by ismaelhamed** [comment]
I guess that depends on what we are really aiming to do here: are we trying to port as much as possible from the `Akka.Http` project (including both Core Dsl and High Dsl), or are we just looking to have the bare minimum to be able to port`Akka.Management` ?

**Comment by Aaronontheweb** [comment]
> are we just looking to have the bare minimum to be able to portAkka.Management ?

For now, definitely this.
