### ISSUE TITLE
Akka.Http.Shim uses Microsoft.AspNetCore 2.2.0, which is not compatible with .NET 5.0

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Akka.Management#23]
As of right now, we're still aiming for .NET Standard 2.0 support, hence why we're using Microsoft.AspNetCore 2.2.0, but it seems like there is no update planned for this package in the future. Including Akka.Http.Shim in a project targetting .NET 5.0 will compile just fine but will fail to run as it will be missing some transient dependencies.

To support .NET 5.0 and up, we would need to do a dual deploy for both .NET Standard 2.0 and .NET 5.0, problem is that they changed the API in the library, so we would need to do conditional coding, and we will have to test the shim in both framework.

**Comment by ismaelhamed** [comment]
I'm leaning towards removing support for AspNetCore 2.x (being this a brand new module), and support only .NET Core 3.1 / .NET5
