### ISSUE TITLE
Cluster.Http: InternalsVisibleTo

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/Akka.Management#232]
I'm currently porting the `Akka.Management.Cluster.Http` module. In my current implementation [I use reflection](https://github.com/ismaelhamed/akka-cluster-management/blob/c5bd962160c32a27551fd25c9e12cef6fffe33b0/src/Akka.Cluster.Management/ClusterHttpManagementRoutes.cs#L84) since both `Cluster.ReadView` and  `ClusterReadView` are internal.

Now that this code will be part of the Akka.NET organization, we should probably decorate `Akka.Cluster` with the `InternalsVisibleTo` attribute:

`[assembly: InternalsVisibleTo("Akka.Management.Cluster.Http,PublicKey=...")`

**Comment by Aaronontheweb** [comment]
I'm fine with adding that to the Akka.Cluster.csproj @ismaelhamed - makes sense to add it as a friend assembly.

**Comment by Aaronontheweb** [comment]
Closed via https://github.com/akkadotnet/akka.net/pull/5363
