### ISSUE TITLE
Update KubernetesClient from 4.0.26 to 12.1.1

### ISSUE THREAD

**Issue by ghost** [akkadotnet/Akka.Management#2349]
The KubernetesClient is very old, which caused some CVEs in our dependency checking tool.
A newer Version should be used.

**Comment by Aaronontheweb** [comment]
Yeah we need to address that - the problem is that none of the newer clients support .NET Standard 2.0, so for the Akka.Kuberenetes.Discovery we might have to drop older runtimes (i.e. use .NET 6.0 or later)
