### ISSUE TITLE
Akka.Discovery: Azure Container Apps & Azure App Services

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Management#638]
**Is your feature request related to a problem? Please describe.**

Need some discovery support for lightweight PaaS options on Azure:

- [x] Azure Container Apps
- [x] Azure App Services (will likely require guidance on how to adjust vNet for custom ports)

**Describe the solution you'd like**

Two separate Akka.Discovery packages, if necessary. If both can be built using the same set of Azure SDK calls, then no problem.

**Comment by Arkatufus** [comment]
Both of these are supported by the new `Akka.Discovery.Azure` package.
