### ISSUE TITLE
Integrate Kestrel/IIS back into Akka.Management

### ISSUE THREAD

**Issue by Arkatufus** [akkadotnet/Akka.Management#736]
## Original problem
Any standalone Kestrel server that tries to start itself up when the hosting web app is set to run "in-process" inside IIS will throw because IIS expect that all servers will be started "in-process".

## Temporary solution
https://github.com/akkadotnet/Akka.Management/pull/729 was introduced as a stop-gap solution for using Akka.Management when the web application is hosted as an "in-process" application inside IIS. We will be using [Ceen-Httpd](https://github.com/kenkendk/ceenhttpd) standalone HTTP server in lieu of Kestrel for the time being.

## Future plan
Ideally we would want to integrate Akka.Management with Kestrel and IIS instead of using the standalone HTTP server inside Akka.Http.Shim, but this will take more time to do and is a blocking issue for implementing Azure platform specific features.

Integrating Akka.Management and Kestrel/IIS would require a major public API overhaul and a major complication in setting up ASP.NET as it would shift a lot of setup steps to the user. Spec is being written about this, will come back to it later.

**Comment by ismaelhamed** [comment]
I thought the `IISHttpServer` included in ASP.NET Core to host apps in-process (via `UseIIS`) was good enough.

**Comment by Aaronontheweb** [comment]
> I thought the `IISHttpServer` included in ASP.NET Core to host apps in-process (via `UseIIS`) was good enough.

Is this something we still need to investigate @Arkatufus ?

**Comment by Aaronontheweb** [comment]
@Arkatufus can this be closed?
