### ISSUE TITLE
Make the AzureDiscoverySetup.AzureCredential of type TokenCredential for flexibility

### ISSUE THREAD

**Issue by Privarozenbeek** [akkadotnet/Akka.Management#860]
Dear Akka developers,

We use Azure for all of the persistence and discovery and we use ManagedIdentityCredential() in our azure environments, but locally we use the DefaultAzureCredential(). Currently the parameter is coupled to DefaultAzureCredential and there fore all other seperate credentials classes are not allowed. They are all implementations of the [TokenCredential class](https://learn.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet). That is why I would suggest to use TokenCredential to support flexibility and not being tied to for excample DefaultAzureCredential.

**Describe the solution you'd like**
I would like to see the TokenCredential class being used as parameter.

**Describe alternatives you've considered**
Since this not a bug that holds us back and more of an improvement we now just disable the undesired credential classes with the [defaultazurecredentialoptions](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet)
![image](https://user-images.githubusercontent.com/102965865/191452185-eb353595-9321-4d68-a63f-f10a33cdea21.png)

This works but less clean.

I would to know your thoughts and possible other ideas on this one. I'm happy to make a pull request for this if you guys agree on this improvement. This same improvement would also be needed for the "Akka.Persistence.Azure.Hosting" extensions if you guys choose to allow this improvement.

Greetings,
Michael

**Comment by Arkatufus** [comment]
That sounds like a good improvement all round, and making the changes on both the core module and Akka.Hosting extension makes a lot of sense. We would welcome any contributions from you.

**Comment by Arkatufus** [comment]
We would need to propagate this change to all Azure related modules in the ecosystem, but that shouldn't be that hard to implement.

**Comment by Arkatufus** [comment]
Ping @Privarozenbeek

**Comment by Privarozenbeek** [comment]
@Arkatufus expect pr(s) related to this soon.

**Comment by Privarozenbeek** [comment]
@Arkatufus i see this pr already for the azure persistence: https://github.com/petabridge/Akka.Persistence.Azure/pull/250 do you still need me to make one for akka.management ?

**Comment by Arkatufus** [comment]
@Privarozenbeek that would be great :)

**Comment by Privarozenbeek** [comment]
@Arkatufus expect a pr somewhere next week.

**Comment by Privarozenbeek** [comment]
@Arkatufus i made the changes in a local branch but unable to push remote. i'm forgetting something?
