### ISSUE TITLE
Cluster doesn't startup when using 0.3.0-beta2 of Akka.Coordination.Azure with managed identity

### ISSUE THREAD

**Issue by wesselkranenborg** [akkadotnet/Akka.Management#961]
**Version Information**
Version of Akka.NET? 1.4.45
Which Akka.NET Modules? Akka.Coordination.Azure -beta2

**Describe the bug**
The cluster doesn't start with this error:
[22/10/24-04:49:08.7710][akka.tcp://system-state-service@10.250.0.161:12552/user/AzureLease3][akka://service/user/AzureLease3][0031]: Failure communicating with the API server for owner service@10.250.0.161:12552 lease service-singleton-akkasystem-state-servicesystemsh: [Value cannot be null. (Parameter 'connectionString')]. Current state: Akka.Coordination.Azure.LeaseActor+PendingRead

**To Reproduce**
Use this Akka.Hosting code to start the cluster (only relevant parts copy/pasted)
```csharp
.WithClustering(
            new ClusterOptions { Roles = new[] { "core" } }
            , new LeaseMajorityOption
            {
                LeaseImplementation = AzureLeaseOption.Instance,
                LeaseName = $"{serviceName}-akka-sbr"
            }
            )
        .WithAzureLease(new AzureLeaseSetup
        {
            AzureCredential = new DefaultAzureCredentials(),
            ContainerName = "akka-coordination-lease"
        })
        .AddHocon(
          @"
            akka.cluster.singleton.use-lease =  ""akka.coordination.lease.azure""
            akka.cluster.sharding.use-lease = ""akka.coordination.lease.azure""",
          HoconAddMode.Prepend)
```

When I comment out the `new LeaseMajorityOption` and `WithAzureLease` and this `AddHocon` part the cluster works flawless.

It seems to me that the check for `connectionString` should not be executed when using Azure Credentials

**Comment by Arkatufus** [comment]
The problem here is lack of feedback from the system, both `AzureCredential` and `ServiceEndpoint` need to be defined in the setup class for the lease to use `AzureCredential`

**Comment by wesselkranenborg** [comment]
So basically, it's a [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK) problem ;-). I'll verify that tomorrow.
